# -*- coding: utf-8 -*-
"""aula05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kv5iRY-VnE5JtbfbpAVAATStJrvsZIvT
"""

from IPython.utils import text
# text = "ola mundo"
# comprimento = len(text)
# print(comprimento)

# y = "guarulhos"
# z = type(y)

# print(z)

# y = False

# z = type(y)

# print(z)

# y = int(input("digite um nº, um texto ou bool : "))

# z = type(y)

# print(z)

# n = "123456"
# x = int(n)
# print (x)

# n = "1.2"
# x = float(n)
# print (x+8)

# lista = {1,2,3,5,6,78,10,12,14}
# print(lista)

# text = "boa tarde"
# lista = {text}
# print(lista)

# tupla = (10,6,5,6.10)
# print(tupla)
# tupla = (456,60,60)
# print(tupla)

# numeros = range(1,6) # Cria uma sequencia de 1 a 5

# numeros = range(1,11, 2 ,3 ,4,5)
# for i in numeros:
# print(i)

# list = (3,6,5,5,5,)
# soma = sum(list)
# print(soma)

# numeros = [3,1,4,1,5,9,2,6,5,3,5]
# print(min(numeros))
# print (max(numeros))

# listas = ["a", "D", "d", "H", "c"]
# lista6 = sorted(listas)
# print(lista6)


# exercicios aula 05

# **Exercício 1:** Escreva um programa que use a função `range()` para gerar os números pares de 2 a 20 e, em seguida, imprima cada número.

# numeros10 = range(5,50)
# for a in numeros10:
#  print(a)

# Exercício 2: Escreva um programa que use a função range() para gerar os múltiplos de 5 de 5 a 50 e, em seguida, calcule e imprima a soma desses múltiplos.

# numeros10 = range(5,50,5)
# for a in numeros10:
#  print(a)

# print(sum(numeros10))


 # **Exercício 3:** Escreva um programa que use a função `type()` para verificar o tipo de uma variável.

# y = input("digite algo")
# print(type(y))


# **Exercício 4:** Escreva um programa que use a função `print()` para imprimir uma mensagem de saudação personalizada, incluindo o nome do usuário.

# nome = input("digite o seu nome")
# print(nome, "ola seja bem vindo ao curso de python")

# Exercício 5: Escreva um programa que use a função range() para gerar os números ímpares de 1 a 10 e, em seguida, calcule e imprima a média desses números.

# numeros05 = range(1,21,2)
# for a in numeros05:
#   print(a)

# print("media", sum(numeros05)/len(numeros05))



# Exercício 1: Escreva um programa que use a função range() para gerar os números pares de 2 a 20 e, em seguida, imprima cada número.

# numeros10 = range(2,21,2)
# for a in numeros10:
#   print(a)

# Exercício 2: Escreva um programa que imprima os números pares de 2 a 20.

# numeros10 = range(2,21,2)
# for a in numeros10:
#   print(a)

# Exercício 3: Escreva um programa que calcule a soma dos números de 1 a 100.

# numeros10 = range(1,100)
# for a in numeros10:
#   print(a)

# print("soma", sum(numeros10))

# Exercício 4: Escreva um programa que imprima os múltiplos de 5 de 5 a 50.

# numeros10 = range(5,50,5)
# for a in numeros10:
#   print(a)

# print(sum(numeros10))

# Exercício 5: Escreva um programa que peça ao usuário para digitar seu nome e imprima cada caractere do nome em uma linha separada.

lista = {}